fix multi-user save error
When multi-user want to save the checkpoint and _retrain_checkpoint.xxx files, and the files have created by the other users, so it says: "
tensorflow.python.framework.errors_impl.PermissionDeniedError: /tmp/checkpoint.tmpxxxx; Operation not permitted."
it will be better save them in the user's folder.