Upgrade TF Hub to protobuf 3.8.0, matching TF 2.1, to fix AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'append'
The bazel configuration to build from source is changes in two ways:
- Hub's py_proto_library() rules are no longer configured to pull in the
  bazel-compiled runtime; they should use the pip package in all cases.
- The WORKSPACE definition gets a unified source for the protobuf library.

PiperOrigin-RevId: 284783317